name: tae
favicon: null
layout_spectrum: 0.34006
typography_spectrum: 0.79485
title: "Hey It's Tae"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130f1e'
    - '#28344a'
    - '#209ca4'
    - '#236072'
    - '#50bea3'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
