name: tae
favicon: null
layout_spectrum: 0.97009
typography_spectrum: 0.0952
title: "Hey It's Tae"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130f1e'
    - '#28344a'
    - '#209ca4'
    - '#236072'
    - '#50bea3'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
